import { type NextPage } from "next";
import Head from "next/head";
import { useQuery } from "urql";

const exampleQuery = `query {
	homePage {
		data {
			attributes {
				goals {
					title
					description
				}
			}
		}
	}
}`;

const Home: NextPage = () => {
  const [result, reexecuteQuery] = useQuery({
    query: exampleQuery,
  });

  return (
    <>
      <Head>
        <title>Developer DAO</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {console.log(result)}
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4"></main>
    </>
  );
};

export default Home;
